server:
  port: 9093
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/Ecommerce-db
    username: khadiuzz
    password: Tawakkul
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
